=== soitun/Rapid/WebContent/WEB-INF/schemas/action.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- 

Copyright (C) 2014 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

RapidSOA is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

	<xs:annotation>
		<xs:documentation>The schema for .action.xml files</xs:documentation>
	</xs:annotation>
	<xs:element name="actions">
		<xs:annotation>
			<xs:documentation>Each .action.xml file can describe several actions
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The action xml is turned into json and loaded
							into the designer where it is used to create new objects
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type">
								<xs:annotation>
									<xs:documentation>The action type is used to uniquely identify
										this control, it should not contain spaces or punctuation
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z0-9_]{1,}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="name">
								<xs:annotation>
									<xs:documentation>The action name is presented to users when
										describing, or logging something about this action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="class">
								<xs:annotation>
									<xs:documentation>Each action must have a Java class, in the
										classpath, that extends com.rapid.desktop.Action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="dependentTypes" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Further control types that this control depends on.
									This will ensure that all necessary resources are created.
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dependentType" maxOccurs="unbounded">								
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>									
								</xs:complexType>							
							</xs:element>
							<xs:element name="addToNewApplications" type="xs:boolean" minOccurs="0">
								<xs:annotation>
									<xs:documentation>If set to true the action will be added to
										new applications when they are created
									</xs:documentation>
								</xs:annotation>
							</xs:element>							
							<xs:element name="properties" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="property" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="key">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="name">
														<xs:annotation>
															<xs:documentation>This is displayed to the users
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>															
														</xs:simpleType>														
													</xs:element>
													<xs:element name="visible" type="xs:boolean"	minOccurs="0">
														<xs:annotation>
															<xs:documentation>Set this optional item to false to not
																render the property
															</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="setConstructValueFunction"
														minOccurs="0">
														<xs:annotation>
															<xs:documentation>Leave this out to not set a property
																value when the control is constructed
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="changeValueJavaScript">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="getValuesFunction" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Possible values that can be used to
																create selects, radio groups, etc
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="refreshProperties" type="xs:boolean" minOccurs="0">
														<xs:annotation>
															<xs:documentation>
															Whether changes to this property cause the control's properties to refresh, useful for "switching" properties that might turn on or off other features
															</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="helpHtml" type="xs:string" minOccurs="0">
														<xs:annotation>
															<xs:documentation>
															The use of this element will add a ? icon next to the property name and a mouse-over tooltip with the contents will be created
															</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="resources" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="resource" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type">
														<xs:annotation>
															<xs:documentation>
																The contents of the plain javascript is written to the rapid.js file and the plain css is written to the application rapid.css file. 
																The javascriptFile and cssFile are written into the html head section includes as links, these are replaced with minified versions for live applications.
																The javascriptLink and cssLink are written into the html head section includes as links, but no minified version are made. 
																The file type resources	are included in the off-line download
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="javascript" />
																<xs:enumeration value="css" />																
																<xs:enumeration value="javascriptFile" />
																<xs:enumeration value="cssFile" />																
																<xs:enumeration value="javascriptLink" />
																<xs:enumeration value="cssLink" />
																<xs:enumeration value="file" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="contents">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="actionJavaScript" minOccurs="0">
								<xs:annotation>
									<xs:documentation>This is the client-side JavaScript that will
										be called, that actually performs the action. Typically the
										properties will be passed in
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="xmlVersion" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>This attribute defines the version of the xml file</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== soitun/Rapid/WebContent/WEB-INF/actions/validation.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>validation</type>
        <name>Validation</name>
	    <class>com.rapid.actions.Validation</class>
	    <helpHtml>This action lets you set benchmarks for carrying out operations. Similar to the Logic action, this action will actively stop further actions from executing until an action is met. A pass action will resume the given action if it is met, such as moving to the next page of a form, and a fail action will keep the user on the same page and trigger some kind of change, such as displaying a validation error.</helpHtml>
	    
	    <addToNewApplications>true</addToNewApplications>
	    
	    <properties>
	        
	        <property>
	            <key>controls</key>
	            <name>Controls</name>
	            <changeValueJavaScript>validationControls</changeValueJavaScript>
	            <refreshProperties>true</refreshProperties>
	            <helpHtml>Sets the control/s on the page to validate against.</helpHtml>
	        </property>
	        
	        <property>
	            <key>showMessages</key>
	            <name>Apply styling</name>
	            <setConstructValueFunction>return true;</setConstructValueFunction>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>
	            <helpHtml>Sets whether to apply a validation style to the selected controls.</helpHtml>
	        </property>
	        
	        <property>
	            <key>stopActions</key>
	            <name>Stop further actions</name>
	            <setConstructValueFunction>return true;</setConstructValueFunction>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>
	            <helpHtml>Sets whether to prevent further actions from being carried out on the page or not, such as progressing to the next page on a form.</helpHtml>
	        </property>
	        
	        <property>
	            <key>passActions</key>
	            <name>Pass actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <refreshProperties>true</refreshProperties>
	            <helpHtml>Sets actions to be carried out for when validation has passed.</helpHtml>
	        </property>
	        
	        <property>
	            <key>failActions</key>
	            <name>Fail actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <refreshProperties>true</refreshProperties>
	            <helpHtml>Sets actions to be carried out for when validation has failed</helpHtml>
	        </property>
	        
	    </properties>
	    
	    <resources>
	        <resource>
	            <type>file</type>
	            <contents>images/alert_16x16.png</contents>
	        </resource>
	                    <resource>
                <type>css</type>
                <contents>
                    <![CDATA[
                                     
div.validation {
	padding: 10px;
	color: red;
	font-weight: bold;
}

label.validation {
	border: 2px solid red;
}

input.validation {
	border: 2px solid red;
}

select.validation {
	border: 2px solid red;
}

textarea.validation {
	border: 2px solid red;
}  

li.validation {
  color:red;
}                  

                    ]]>
                </contents>                
            </resource> 
	    </resources>
	    	    	    
	    <actionJavaScript>
	        <![CDATA[   
function Action_validation(ev, validations, showMessages) {
	var valid = true;		
	for (var i in validations) {
		var validation = validations[i];
		var validationControl = $("#" + validation.controlId);
		if (validationControl[0]) {		
			var getValueFunction = null;
			if (validation.validationProperty) {
				getValueFunction = window["getProperty_" + validation.controlType + "_" + validation.validationProperty];
			} else {
				getValueFunction = window["getData_" + validation.controlType];
			}
			if (getValueFunction) {
				var details = null;
				if (validation.details) {
					if (validation.details.indexOf("{") == 0) {
						details = JSON.parse(details);
					} else {
						details = window[validation.details];
					}
				}
				var value = getValueFunction(ev, validation.controlId, validation.field, details);
				if (validation.validationType == "javascript") {						
					var validationFunction = new Function(["ev","id","value"], validation.javaScript);
					var failMessage = validationFunction.apply(this, [ev,validation.controlId,value]);
					if (failMessage != null && failMessage !== false && failMessage !== undefined) {
						if (showMessages) showControlValidation(validation.controlId, failMessage);
						valid = false;
					} else {
						if (showMessages) hideControlValidation(validation.controlId);
					}
				} else {
					// assume no pass
					var pass = false;
					// start with some basic checks
					if (value && value != "false") {
						// get the regex expression
						var exp = validation.regEx.trim();
						// make a regex
						var regex = new RegExp(exp);
						// if the expression ends with /i
						if (exp.indexOf("/i") == exp.length - 2) {
							// update the exp removing the /i
							exp = exp.substr(0, exp.length - 2);
							// remake the regex with the case insensitivity
							regex = new RegExp(exp, "i")
						} 					
						// get the matches from the reg ex
						var matches = value.match(regex);
						// ensure the first match is for the whole value
						if (matches) {
							// got some matches now groups must match too
							if (matches.length == 1) {
								// these are the easy ones
								pass = true;
							} else {
								// we now need to loop all of the groups
								for (var i in matches) {
									if (i != "index" && i != "input" && matches[i] == value) {
										// we're good
										pass = true;
										break;
									}
								}
							}
						} 
					} else if (validation.allowNulls) {
						// no value but this is allowed
						pass = true;
					}
					// pass, disabled, or hidden and allowed this way
					if (pass || validationControl.is(":disabled") || (validationControl.is(":hidden") && validation.passHidden)) {
						// passed
						if (showMessages) hideControlValidation(validation.controlId);				
					} else {
						// failed, and there is a message to show, but not on tab keyup
						if (showMessages && !(ev.type == "keyup" && ev.keyCode == 9)) showControlValidation(validation.controlId, validation.message);
						valid = false;					
					}	
				}	
			} else {
				if (showMessages) showControlValidation(validation.controlId, validation.message);
				valid = false;
			}
		}		
	}	
	return valid;
}	        ]]>
	    </actionJavaScript> 
	    
    </action> 
    
</actions>

=== soitun/Rapid/WebContent/WEB-INF/actions/group.action.xml
<?xml version="1.0" encoding="UTF-8" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>group</type>
        <name>Group</name>
	    <class>com.rapid.actions.Group</class>
	    <helpHtml>Enables multiple action calls in a single event. This is useful for when you want to trigger many events without taking up a lot of space. Related actions can be recalled, be formed in logical groups and can be reused in a single step. Grouped actions are also useful for page reuse events.</helpHtml>
	      
	    <properties>
	        
	         <property>
	            <key>description</key>
	            <name>Description</name>
	            <changeValueJavaScript>bigtext</changeValueJavaScript>
	            <helpHtml>A description of the actions in this group.</helpHtml>
	        </property>
	        
	        <property>
	            <key>actions</key>
	            <name>Actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Add actions to this group to tidy your application, or re-use all actions in the group.</helpHtml>
	        </property>
	        	            
	    </properties>
	    	   	    	    	    	    	     	     	    
    </action>
</actions>
