=== soitun/Rapid/WebContent/WEB-INF/schemas/action.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- 

Copyright (C) 2014 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

RapidSOA is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

	<xs:annotation>
		<xs:documentation>The schema for .action.xml files</xs:documentation>
	</xs:annotation>
	<xs:element name="actions">
		<xs:annotation>
			<xs:documentation>Each .action.xml file can describe several actions
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The action xml is turned into json and loaded
							into the designer where it is used to create new objects
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type">
								<xs:annotation>
									<xs:documentation>The action type is used to uniquely identify
										this control, it should not contain spaces or punctuation
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z0-9_]{1,}" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="name">
								<xs:annotation>
									<xs:documentation>The action name is presented to users when
										describing, or logging something about this action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="class">
								<xs:annotation>
									<xs:documentation>Each action must have a Java class, in the
										classpath, that extends com.rapid.desktop.Action
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="dependentTypes" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Further control types that this control depends on.
									This will ensure that all necessary resources are created.
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dependentType" maxOccurs="unbounded">								
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>									
								</xs:complexType>							
							</xs:element>
							<xs:element name="addToNewApplications" type="xs:boolean" minOccurs="0">
								<xs:annotation>
									<xs:documentation>If set to true the action will be added to
										new applications when they are created
									</xs:documentation>
								</xs:annotation>
							</xs:element>							
							<xs:element name="properties" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="property" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="key">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="name">
														<xs:annotation>
															<xs:documentation>This is displayed to the users
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>															
														</xs:simpleType>														
													</xs:element>
													<xs:element name="visible" type="xs:boolean"	minOccurs="0">
														<xs:annotation>
															<xs:documentation>Set this optional item to false to not
																render the property
															</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="setConstructValueFunction"
														minOccurs="0">
														<xs:annotation>
															<xs:documentation>Leave this out to not set a property
																value when the control is constructed
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="changeValueJavaScript">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="getValuesFunction" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Possible values that can be used to
																create selects, radio groups, etc
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="refreshProperties" type="xs:boolean" minOccurs="0">
														<xs:annotation>
															<xs:documentation>
															Whether changes to this property cause the control's properties to refresh, useful for "switching" properties that might turn on or off other features
															</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="helpHtml" type="xs:string" minOccurs="0">
														<xs:annotation>
															<xs:documentation>
															The use of this element will add a ? icon next to the property name and a mouse-over tooltip with the contents will be created
															</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="resources" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="resource" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type">
														<xs:annotation>
															<xs:documentation>
																The contents of the plain javascript is written to the rapid.js file and the plain css is written to the application rapid.css file. 
																The javascriptFile and cssFile are written into the html head section includes as links, these are replaced with minified versions for live applications.
																The javascriptLink and cssLink are written into the html head section includes as links, but no minified version are made. 
																The file type resources	are included in the off-line download
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="javascript" />
																<xs:enumeration value="css" />																
																<xs:enumeration value="javascriptFile" />
																<xs:enumeration value="cssFile" />																
																<xs:enumeration value="javascriptLink" />
																<xs:enumeration value="cssLink" />
																<xs:enumeration value="file" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="contents">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="actionJavaScript" minOccurs="0">
								<xs:annotation>
									<xs:documentation>This is the client-side JavaScript that will
										be called, that actually performs the action. Typically the
										properties will be passed in
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="xmlVersion" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>This attribute defines the version of the xml file</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== soitun/Rapid/WebContent/WEB-INF/actions/webservice.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>webservice</type>
        <name>Webservice</name>
	    <class>com.rapid.actions.Webservice</class>
	    <helpHtml>Used for computer to computer communication, the webservice action allows you to set the request type to SOAP, restful XML or JSON. SOAP follows a strict set of rules which must be met in order for a request to go through, restful XML is less strict, and JSON has no set of rules but will block the request if it is unsuccessful..</helpHtml>
	    
	    <addToNewApplications>true</addToNewApplications>
	    
	    <properties>
	        
	        <property>
	            <key>request</key>
	            <name>Request</name>
	            <changeValueJavaScript>webserviceRequest</changeValueJavaScript>
	            <helpHtml>Enables you to define a webservice request. The request can be entered within the text area and can be of the type SOAP, JSON or XML/Restful. Selected inputs and outputs can be chosen for the request.</helpHtml>
	        </property>
	         
	        <property>
	            <key>showLoading</key>
	            <name>Loading animation</name>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>
	            <helpHtml>Sets whether to display a loading animation or not whilst the request is taking place.</helpHtml>
	        </property>
	        
	        <property>
	            <key>successActions</key>
	            <name>Success actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Sets actions to be carried out for when the webservice has completed successfully.</helpHtml>
	        </property>
	        
	        <property>
	            <key>errorActions</key>
	            <name>Error actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Sets actions to be carried out for when the webservice has not been successful.</helpHtml>
	        </property>
	            
	    </properties>
	    
	    <resources>
	        <resource>
	    		<type>file</type>
	    		<contents>images/wait_120x15.gif</contents>
	    	</resource>
	    	<resource>
	    		<type>javascript</type>
	    		<contents>
	    			<![CDATA[
// this global associative array tracks the webserviceAction call sequences for each action	    			
var _webserviceActionSequence = [];	    

// this global associative array holds the greates sequence received back     			
var _webserviceActionMaxSequence = [];	

// this function returns an incrementing sequence for each database action call so long-running slow queries don't overrwrite fast later queries
function getWebserviceActionSequence(actionId) {
	// retrieve the current sequence for the action
	var sequence = _webserviceActionSequence[actionId];
	// if null set to 0
	if (!sequence) sequence = 0
	// increment
	sequence++;
	// store
	_webserviceActionSequence[actionId] = sequence;
	// pass back
	return sequence;
}	

// this function sets the max to 0 if null
function getWebserviceActionMaxSequence(actionId) {
	// retrieve the current sequence for the action
	var sequence = _webserviceActionMaxSequence[actionId];
	// if undefined
	if (sequence === undefined) {
		// set to 0
		sequence = 0;
		// retain for next time
		_webserviceActionMaxSequence[actionId] = sequence;
	}
	// pass back
	return sequence;
}			
	    			]]>
	    		</contents>
	    	</resource>
	    </resources>
	    	 
	    <actionJavaScript>
	        <![CDATA[ 
function Action_webservice(ev, actionId, data, outputs) {
	// only if there are data and outputs
	if (data && outputs) {
		// only if this is the latest sequence
		if (data.sequence > getWebserviceActionMaxSequence(actionId)) {
			// retain this as the lastest sequence
			_webserviceActionMaxSequence[actionId] = data.sequence;
			// loop the outputs
			for (var i in outputs) {
				var output = outputs[i];			
				window["setData_" + output.type](ev, output.id, output.field, output.details, data);
			}
		}
	}
}	        ]]>
	    </actionJavaScript>   
	    
    </action> 
</actions>

=== soitun/Rapid/WebContent/WEB-INF/actions/existing.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>existing</type>
        <name>Existing</name>
	    <class>com.rapid.actions.Existing</class>
	    <helpHtml>Enables you to call an existing event on that specific page. If the event being referenced here is removed then it will display as a blank event, meaning you are free to delete or change the event target as the previous one is no longer present.</helpHtml>
	    
	    <addToNewApplications>true</addToNewApplications>

		<properties>
	        <property>
	            <key>action</key>
	            <name>Action</name>
	            <changeValueJavaScript>select</changeValueJavaScript>
	            <getValuesFunction>
	                <![CDATA[
return "<option value=''>None</option>" + getExistingActionOptions(this.action, this.id);
	                ]]>
	            </getValuesFunction>
	            <helpHtml>Allows the reuse of other, existing actions on other controls, including the page.</helpHtml>
	        </property>
	    </properties>
  
    </action>
</actions>

=== soitun/Rapid/WebContent/WEB-INF/actions/timer.action.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">
 
 <!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->
 
    <action>
    
        <type>timer</type>
        <name>Timer</name>
	    <class>com.rapid.actions.Timer</class>
	    <helpHtml>This action adds a delay to other actions, making them occur after a pre-determined period of time, defaulting to 1 second. This can also be set to repeat. This can be useful for making users wait whilst a back-end change takes place.</helpHtml>
	    
	    <properties>
	        
	        <property>
	            <key>duration</key>
	            <name>Duration (milliseconds)</name>
	            <setConstructValueFunction>return 1000;</setConstructValueFunction>
	            <changeValueJavaScript>integer</changeValueJavaScript>
	            <helpHtml>Sets how long the timer will last.</helpHtml>
	        </property>
	            	
	    	<property>
	            <key>repeat</key>
	            <name>Repeat</name>
	            <setConstructValueFunction>return false;</setConstructValueFunction>
	            <changeValueJavaScript>checkbox</changeValueJavaScript>
	            <helpHtml>Allows you to define whether to repeat the timer action after the ellapsed time has passed.</helpHtml>
	        </property>
	        
	        <property>
	            <key>actions</key>
	            <name>Actions</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Defines the actions to be carried out after the set duration of time has ellapsed.</helpHtml>
	        </property>
	        
	    </properties>
	        	      	    
    </action> 
    
</actions>

=== soitun/Rapid/WebContent/WEB-INF/actions/logic.action.xml
<?xml version="1.0" encoding="UTF-8" ?>
<actions xmlVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/action.xsd">

<!-- 

Copyright (C) 2016 - Gareth Edwards / Rapid Information Systems

gareth.edwards@rapid-is.co.uk


This file is part of the Rapid Application Platform

Rapid is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version. The terms require you to include
the original copyright, and the license notice in all redistributions.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
in a file named "COPYING".  If not, see <http://www.gnu.org/licenses/>.

 -->

    <action>
    
        <type>logic</type>
        <name>Logic</name>
	    <class>com.rapid.actions.Logic</class>
	    <helpHtml>This action allows you to contest certain outcomes and have different success or fail actions occur as a result. Multiple success and failure actions can be stacked inside one another and a variety of different conditions can be tested against, making this action a very powerful and flexible tool to use in a variety of different ways, such as only displaying a page if visibility rules are met.</helpHtml>
	    
	    <addToNewApplications>true</addToNewApplications>
	    	    	    	    
	    <properties>
	        
	         <property>
	            <key>conditions</key>
	            <name>Conditions</name>
	            <changeValueJavaScript>logicConditions</changeValueJavaScript>
	            <refreshProperties>true</refreshProperties>
	            <helpHtml>Sets the conditions for the logic to be carried out. This can be particularly useful for setting controls to appear on the page, or checking for correct details on the page.</helpHtml>
	        </property>
	        
	        <property>
	            <key>conditionsType</key>
	            <name>Type</name>
	            <visible>false</visible>
	            <setConstructValueFunction>return "and";</setConstructValueFunction>
	            <changeValueJavaScript>text</changeValueJavaScript>
	        </property>
	        
	        <property>
	            <key>trueActions</key>
	            <name>Actions if true</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Defines the actions to be carried out if the above condition is true.</helpHtml>
	        </property>
	        
	        <property>
	            <key>falseActions</key>
	            <name>Actions if false</name>
	            <changeValueJavaScript>childActions</changeValueJavaScript>
	            <helpHtml>Defines the actions to be carried out if the above condition is false.</helpHtml>
	        </property>
	            
	    </properties>
	    	   	    	    	    	    	     	     	    
    </action>
</actions>
